# Generated by Django 4.1.6 on 2023-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("service", models.CharField(max_length=100)),
                ("budget", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Quote",
            },
        ),
    ]
